{% set version = "0.3.5" %}

package:
  name: glog
  version: {{ version }}

source:
  fn: glog-{{ version }}.tar.gz
  url: https://github.com/google/glog/archive/v{{ version }}.tar.gz
  sha256: 7580e408a2c0b5a89ca214739978ce6ff480b5e7d8d7698a2aa92fadc484d1e0
  patches:
    # Work around clang bug that does not raise SIGFPE
    - 0001-Always-raise-SIGFPE.patch  # [osx]
    - 0002-tests-fix-compilation-with-C-17.patch
    - 0003-Remove-non-existent-USAGE-level-from-tests.patch

build:
  number: 1000
  skip: true  # [win]

requirements:
  build:
    - autoconf
    - automake
    - libtool
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

test:
  commands:
    - test -f ${PREFIX}/lib/libglog.dylib            # [osx]
    - test -f ${PREFIX}/lib/libglog.so               # [linux]

about:
  home: https://github.com/google/glog
  license: BSD 3-Clause
  license_file: COPYING
  summary: C++ implementation of the Google logging module.

extra:
  recipe-maintainers:
    - jakirkham
    - xhochy
